name: CI/CD for ethers-wallet-ts-package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      # 3. Install dependencies
      - run: npm ci

      # 4. Run build
      - run: npm run build

      # 5. Run tests (right now your test script just echoes "No tests")
      - run: npm test

      # 6. Publish to npm
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
